### ISSUE TITLE
6장 내용 수정 건의

### ISSUE THREAD

**Issue by marshallku** [bbodeuk/Clean-Code#1]
## `constructor` 추가

https://github.com/bbodeuk/Clean-Code/blob/44162dbcea5b5de0d124ecbb4098fa380371c267/docs/6%EC%9E%A5%20-%20%EA%B0%9D%EC%B2%B4%EC%99%80%20%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0.md?plain=1#L56-L65

```ts
class Square {
    topLeft: Point;
    side: number;

    constructor(topLeft: Point, side: number) {
        this.topLeft = topLeft;
        this.side = side;
    }
}

class Rectangle {
    topLeft: Point;
    height: number;
    width: number;

    // ...
}
```

`constructor`를 추가하거나, 후략을 표시해주는 게 좋지 않을까요?

## 불필요한 ``else`` 및 타입 단언 제거

https://github.com/bbodeuk/Clean-Code/blob/44162dbcea5b5de0d124ecbb4098fa380371c267/docs/6%EC%9E%A5%20-%20%EA%B0%9D%EC%B2%B4%EC%99%80%20%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0.md?plain=1#L67-L78

```ts
class Geometry {
    area(shape: Object) {
        if (shape instanceof Square) {
            return shape.side * shape.side;
        }

        if (shape instanceof Rectangle) {
            return shape.height * shape.width;
        }

        throw new Error("No Such Shape");
    }
}
```

조건문에서 `return`이 이뤄지면 `else`절에 걸릴 일이 없으니 생략하는 게 조금 더 논리적이지 않을까 싶습니다.\
추가로, `instanceof`으로 판별한 뒤엔 `shape`의 타입이 확정되므로, 불필요한 타입 단언은 제거해도 좋을 것 같습니다.

## `private`에 대한 설명 추가

https://github.com/bbodeuk/Clean-Code/blob/44162dbcea5b5de0d124ecbb4098fa380371c267/docs/6%EC%9E%A5%20-%20%EA%B0%9D%EC%B2%B4%EC%99%80%20%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0.md?plain=1#L124-L145

```ts
class ClassWithECMAPrivateField {
    #privateField;

    constructor() {
        this.#privateField = 42;
    }
}

class ClassWithPrivateField {
    private privateField;

    constructor() {
        this.privateField = 42;
    }
}
```

`ClassWithECMAPrivateField`의 `privateField`는 런타임에서도 접근이 불가능한 반면, `ClassWithPrivateField`의 `privateField`는 컴파일 단계에서만 접근이 불가능합니다.

**참고**

* [MDN - Private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)
* [TypeScript: Documentation - Classes](https://www.typescriptlang.org/docs/handbook/2/classes.html#private)
* [Stackoverflow - What are the differences between the private keyword and private fields in TypeScript?](https://stackoverflow.com/questions/59641564/what-are-the-differences-between-the-private-keyword-and-private-fields-in-types)

**Comment by 0sinf** [comment]
private 관련 참고자료

[Announcing TypeScript 3.8 Beta](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#ecmascript-private-fields)
